import PrincipalClosure
import PositiveNormalizerQuotient

namespace JSP400

open Matrix Set

/-- The topological closure of the subgroup generated by the literal
normalizer intersection N(V₁) ∩ closure(V₁ M V₁), as in Lemma 5(II). -/
def principalEnlargementGroup (M : Set SL3) : Subgroup SL3 :=
  (Subgroup.closure ((Subgroup.normalizer (principalUnipotent : Set SL3) : Set SL3) ∩
    closure (principalDoubleOrbit M))).topologicalClosure

theorem principalNormalizerReturn_subset_enlargementGroup (M : Set SL3) :
    principalNormalizerReturn M ⊆ (principalEnlargementGroup M : Set SL3) := by
  intro g hg
  apply Subgroup.le_topologicalClosure
  exact Subgroup.subset_closure ⟨hg.1, hg.2.1⟩

theorem principalUnipotent_le_enlargementGroup (M : Set SL3)
    (hbase : (1 : SL3) ∈ closure M) : principalUnipotent ≤ principalEnlargementGroup M := by
  intro g hg
  have hn : g ∈ Subgroup.normalizer (principalUnipotent : Set SL3) :=
    principalUnipotent.le_normalizer hg
  have hc : g ∈ closure (principalDoubleOrbit M) := by
    obtain ⟨t, rfl⟩ := hg
    have hcont : Continuous (fun m : SL3 => unipotentOne t * m) := continuous_const.mul continuous_id
    have hi := mem_closure_image hcont.continuousAt hbase
    simp only [mul_one] at hi
    apply closure_mono ?_ hi
    rintro h ⟨m, hm, rfl⟩
    exact ⟨t, m, hm, 0, by rw [unipotentOne_zero, mul_one]⟩
  apply Subgroup.le_topologicalClosure
  exact Subgroup.subset_closure ⟨hn, hc⟩

/-- The complete matrix-group alternative in Margulis Lemma 5(II). All
normalizer enlargement, orbit sections, non-discreteness and closed affine
subgroup classification have been proved for the actual groups. -/
theorem margulis_lemma5_II_alternative (M : Set SL3)
    (hbase : (1 : SL3) ∈ closure M) (hout : ∀ g ∈ M, g ∉ principalUnipotent) :
    (∀ b : ℝ, unipotentTwo b ∈ principalEnlargementGroup M) ∨
      ∃ r : ℝ, ∀ t : ℝ, ∀ ht : 0 < t,
        unipotentTwo r * diagonalFlow t (ne_of_gt ht) * (unipotentTwo r)⁻¹ ∈
          principalEnlargementGroup M := by
  apply closed_matrix_subgroup_affine_alternative (principalEnlargementGroup M)
    (Subgroup.isClosed_topologicalClosure _) (principalUnipotent_le_enlargementGroup M hbase)
    (principalNormalizerReturn M) (principal_normalizer_enlargement M hbase hout)
  intro g hg
  exact ⟨principalNormalizerReturn_subset_enlargementGroup M hg, hg.1, hg.2.2⟩

/-- The original generated-group conclusion, including the V₁ factor in the
conjugate DV₁ subgroup rather than just the diagonal subgroup. -/
theorem margulis_lemma5_II (M : Set SL3)
    (hbase : (1 : SL3) ∈ closure M) (hout : ∀ g ∈ M, g ∉ principalUnipotent) :
    shearGroup ≤ principalEnlargementGroup M ∨
      ∃ v ∈ shearGroup, ∀ t : ℝ, ∀ ht : 0 < t, ∀ u ∈ principalUnipotent,
        v * (diagonalFlow t (ne_of_gt ht) * u) * v⁻¹ ∈ principalEnlargementGroup M := by
  have hV := principalUnipotent_le_enlargementGroup M hbase
  rcases margulis_lemma5_II_alternative M hbase hout with hv | hd
  · apply Or.inl
    rintro g ⟨a, b, rfl⟩
    rw [shearElement_unipotent_factor]
    exact (principalEnlargementGroup M).mul_mem (hV ⟨a, rfl⟩) (hv _)
  · obtain ⟨r, hr⟩ := hd
    refine Or.inr ⟨unipotentTwo r, ⟨0, r, ?_⟩, ?_⟩
    · apply Subtype.ext
      ext i j
      fin_cases i <;> fin_cases j <;> simp [unipotentTwo, shearElement]
    · intro t ht u hu
      have hn := unipotentTwo_mem_principalNormalizer r
      have hconj := (Subgroup.mem_set_normalizer_iff.mp hn) u
      have hcu : unipotentTwo r * u * (unipotentTwo r)⁻¹ ∈ principalUnipotent := hconj.mp hu
      have h := (principalEnlargementGroup M).mul_mem (hr t ht) (hV hcu)
      simpa only [mul_assoc, inv_mul_cancel_left] using h

end JSP400

#print axioms JSP400.margulis_lemma5_II
